version: "3.8"
services:
  nginx:
    build: ./nginx
    image: nginx
    container_name: nginx_container
    ports:
      - 8000:8000
    depends_on:
      - app
  app:
    build: ./project
    volumes:
      - ./project:/django
    ports:
      - 8001:8001
    image: app:django
    container_name: django_container
    command: gunicorn project.wsgi --bind 0.0.0.0:8001
    depends_on:
      - db 
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    container_name: postgres_db
 

